### ISSUE TITLE
Slow on ASCII chars. Maybe check them first?

### ISSUE THREAD

**Issue by faho** [ridiculousfish/widecharwidth#1]
Soo... I made fish_wcwidth a ton faster by adding this to the beginning:

```c++
    // Normal ASCII characters.
    // These are the most common case, so it's worth checking them first.
    if (wc < 0x7f && wc >= 0x20) return 1;
```

I would wager that, given how prevalent these characters are in any machine-generated text (source code, but also HTML, json et al), that it's quite worth it to check them first, as opposed to returning 1 after checking everything else.

**Comment by ridiculousfish** [comment]
cool
