### ISSUE TITLE
Erroneous comment!

### ISSUE THREAD

**Issue by SlySven** [ridiculousfish/widecharwidth#12]
https://github.com/ridiculousfish/widecharwidth/blob/5aeade7b3094399ec6e669c681c9fdf4132cdd02/widechar_width.h#L29

These ranges of character are nothing to do with **surrogates** (the means by which UTF-16 conveys Unicode codepoints beyond the BMP {*basic multi plane*} as pairs of code points). UTF-16, just like UTF-8, has been a *variable length encoding* since somewhere around Unicode 3.0 IIRC - which causes problems for coders {and some coding languages and libraries} that failed to remember this and think that *16* bits are enough to store a **whole** Unicode code point.

Instead they are codepoints that must be treated as **valid** as data but which are ***never*** going to be declared for use by the Unicode consortium so can be used *internally* by an application...

**Comment by ridiculousfish** [comment]
My bad, I somehow assumed that the surrogate range overlapped with the non-character range in the BMP. Thanks for the fix!
