### ISSUE TITLE
Hangul Jamo vowels and trailing consonants should probably be 0 width

### ISSUE THREAD

**Issue by ninjalj** [ridiculousfish/widecharwidth#16]
I've been looking at widths reported for Hangul Jamo in wcwidth implementations.

In glibc and MirBSD xterm, U+1160..U+11FF and U+D7B0..U+D7FF have 0 width.

In xterm/ncurses, glib(g_unichar_iszerowidth), and rust's
unicode-width U+1160..U+11FF have 0 width.

Konsole had U+1160..U+11FF with 0 width until October 2018, but moving
from a wcwidth() based on the Markus Kuhn one to one generated from
Unicode datafiles caused it to return width 1
(https://bugs.kde.org/show_bug.cgi?id=396435#c21).

musl, libunistring, vim/NeoVim, seem to know
nothing about Hangul Jamo, and return width 1.

Some context follows:

Korean Hangul is a writing system which uses syllable blocks
consisting of alphabetic components. A syllable consists of one or
more Leading Consonants, one or more Vowels, and zero or more trailing
consonants.

Unicode has precomposed syllable blocks at U+AC00..U+D7A3 (11172).

There are also component Jamos:

Hangul Jamo (U+1100..U+11FF).

U+1100..U+115F Choseong (initial, Leading Consonants) have
East_Asian_Width=Wide and Hangul_Syllable_Type=Leading_Jamo
U+1160..U+11A7 Jungseong (medial, Vowels) have
East_Asian_Width=Neutral and Hangul_Syllable_Type=Vowel_Jamo
U+11A8..U+11FF Jongseong (final, Trailing consonants) have
East_Asian_Width=Neutral and Hangul_Syllable_Type=Trailing_Jamo

U+A960..U+A97F Hangul Jamo Extended-A (choseong) have East_Asian_Width=Wide
U+D7B0..U+D7FF Hangul Jamo Extended-B (jungseong and jongseong) have
East_Asian_Width=Neutral
U+3130..U+318F Hangul Compatibility Jamo have no conjoining behavior
U+FFA0..U+FFDF half-width forms have no conjoining behavior.

U+1100..U+11FF, U+A960..U+A97F, U+D7B0..U+D7FF have conjoining
behavior, a sequence of L+V+T* gets rendered as a syllable block.
wcwidth() implementations tend to give U+1100..U+115F width 2, and
U+1160..U+11FF width 0, so the resulting syllable block has the
correct total width.

U+D7B0..U+D7FF, should also have width 0.

glibc gave width 0 to conjoining jungseong and jongseong at:

```
commit 7a79e321c6f85b204036c33d85f6b2aa794e7c76
Author: Thorsten Glaser <tg@mirbsd.de>
Date:   Fri Jul 14 14:02:50 2017 +0200

    Refresh generated charmap data and ChangeLog

            [BZ #21750]
            * charmaps/UTF-8: Refresh.

diff --git a/localedata/ChangeLog b/localedata/ChangeLog
index 04ef5ad071..9e05b4a652 100644
--- a/localedata/ChangeLog
+++ b/localedata/ChangeLog
@@ -1,3 +1,17 @@
+2017-07-14  Thorsten Glaser  <tg@mirbsd.de>
+
+       [BZ #21750]
+       * charmaps/UTF-8: Refresh.
+       * unicode-gen/utf8_gen.py (U+00AD): Set width to 1.
+       * unicode-gen/utf8_gen.py (U+1160..U+11FF): Set width to 0.
+       * unicode-gen/utf8_gen.py (U+3248..U+324F): Set width to 2.
+       * unicode-gen/utf8_gen.py (U+4DC0..U+4DFF): Likewise.
+       * unicode-gen/utf8_gen.py: Treat category Me and Mn as combining.
+       [BZ #19852]
+       * unicode-gen/utf8_gen.py: Process EastAsianWidth lines before
+       UnicodeData lines so the latter have precedence; remove hack
+       to group output by EastAsianWidth ranges.
+

```
[ ... snip ...]

```
commit 6e540caa21616d5ec5511fafb22819204525138e
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Tue Jun 16 08:29:40 2020 +0200

    Set width of JUNGSEONG/JONGSEONG characters from UD7B0 to UD7FB to
0 [BZ #26120]
Reviewed-by: default avatarCarlos O'Donell <carlos@redhat.com>

diff --git a/localedata/charmaps/UTF-8 b/localedata/charmaps/UTF-8
index 14c5d4fa33..8cce47cd97 100644
--- a/localedata/charmaps/UTF-8
+++ b/localedata/charmaps/UTF-8
@@ -48920,6 +48920,8 @@ WIDTH
 <UABE8>        0
 <UABED>        0
 <UAC00>...<UD7A3>      2
+<UD7B0>...<UD7C6>      0
+<UD7CB>...<UD7FB>      0
 <UF900>...<UFA6D>      2
 <UFA70>...<UFAD9>      2
 <UFB1E>        0

```

**Comment by krobelus** [comment]
Sounds reasonable, I've written a change to match glibc in https://github.com/ridiculousfish/widecharwidth/pull/17
I'm wondering if there's a practical motivation for this, and of course, if there is a (planned) feature in Unicode that we can use instead of hardcoding this?

**Comment by ninjalj** [comment]
The better solution would be to have an API that takes a string, or at least a grapheme cluster (extended?), and returns the width of the whole thing. For Hangul, each syllable, which should be its own grapheme cluster, should have width 2.

An example of an API like that would be perl's Unicode::GCString (grapheme cluster string):

```
use strict;
use warnings;

binmode(STDOUT, ":utf8");

use Unicode::GCString;
use Text::CharWidth qw(mbwidth mbswidth);

sub string_info {
        my $s = shift;
        my $gc = Unicode::GCString->new($s);
        print "$s : GCString->columns: ", $gc->columns, " : mbswidth: ", mbswidth($s), "\n";
        for (my $i = 0; $i < length($s); $i++) {
                my $c = substr($s,$i,1);
                my $cgc = Unicode::GCString->new($c);
                print "\t$c : GCString->columns: ", $cgc->columns, " : mbswidth: ", mbswidth($c), " : mbwidth: ", mbwidth($c), "\n";
        }
}

string_info("\x{1100}\x{d7b0}\x{d7fb}\x{1101}\x{d7c0}\x{d7c2}\x{d7d0}");
string_info("\x{1100}\x{200b}\x{d7b0}\x{200b}\x{d7fb}\x{1101}\x{200b}\x{d7c0}\x{200b}\x{d7c2}\x{200b}\x{d7d0}");
string_info("\x{fefb}");
string_info("\x{644}\x{627}");
string_info("\x{644}\x{625}");
string_info("\x{644}\x{623}");
string_info("\x{644}\x{622}");
```

Which, modulo some spacing issues and a total lack of forming the mandatory Arabic LAM+ALEF ligature, should look something like:

![Screenshot_20211229_011052](https://user-images.githubusercontent.com/93227013/147615992-3087465b-8650-4e79-aaaa-aff96758de50.png)

There, `Unicode::GCString` mostly gets the correct answers, and `Text::CharWidth` gives typical answers for  `wcwidth()/wcswidth()` style APIs.

Another corner case is the aforementioned LAM+ALEF ligature. In Arabic, LAM ALEF must always be substituted for a ligature, which typically takes 1 cell. Using the ligature from the Presentation Forms (which should not be used, they are for compatibility with legacy HW/SW), you get the correct ligature, and the correct width of 1 column. Using LAM and ALEF, many terminal emulators don't do Arabic shaping at all (BAD), and an incorrect width of 2 is returned (2 BADs don't really make it right). Vim has special code to deal with the LAM+ALEF ligature: https://github.com/vim/vim/blob/52797bae1710621926c03a2611c40a692c96fb44/src/mbyte.c#L1920

**Comment by krobelus** [comment]
> The better solution would be to have an API that takes a string, or at least a grapheme cluster (extended?), and returns the width of the whole thing.
> [...]

yeah, wcwidth(3) is fundamentally broken for combining characters (I think these allow you to combine two emoji to get a different emoji etc.).

> There, `Unicode::GCString` mostly gets the correct answers, and `Text::CharWidth` gives typical answers for  `wcwidth()/wcswidth()` style APIs.

So you are saying that wcswidth(3) is also broken? Surely that can be fixed.

Exposing a widecharwidth_wcswidth would be great (would be a nice improvement for fish) but it sounds like a lot of work, and I don't think it's related to your original issue? Or would wcswidth implementations count incomplete Hangul syllables as width 0?

I think this is roughly why this project exists in the first place
1. macOS and other systems ships a very old version of wcwidth.
2. To properly display emoji, some terminals ship their own wcwidth
3. That makes things worse because terminal applications get inconsistent across terminals (and there is no way to query that).
4. Some terminal applications ship their own wcwidth

When navigating characters in fish, the cursor visits every code point.
Fixing that to work on grapheme clusters would be a nightmare.
Curiously, there are also single Hangul characters for entire syllables which could be used to work around this...

**Comment by ninjalj** [comment]
> So you are saying that wcswidth(3) is also broken? 

Nope. I'm saying (all?) wcswidth() implementations just call wcwidth() in a loop and call it a day. There's still some hope for the future (https://sourceware.org/bugzilla/show_bug.cgi?id=22074#c4).
 
> Exposing a widecharwidth_wcswidth would be great (would be a nice improvement for fish) but it sounds like a lot of work, and I don't think it's related to your original issue? 

The proximate cause for this report would be https://github.com/wez/wezterm/issues/1469. The distal cause would be just me seeing https://github.com/wez/wezterm/issues/1469 and starting to investigate.

> Or would wcswidth implementations count incomplete Hangul syllables as width 0?

Ideally, they should count as width 2, see GCString above.

> Curiously, there are also single Hangul characters for entire syllables which could be used to work around this...

MacOS X stores filenames in NFD. Causing trouble for Neovim+Nerdtree: https://github.com/neovim/neovim/issues/4476

In any case, #17 should fix wezterm's assert, in which case this issue can be closed.
