### ISSUE TITLE
Whitespace?

### ISSUE THREAD

**Issue by Artoria2e5** [ridiculousfish/widecharwidth#28]
Right now U+0020 gives `widechar_nonprint` (in the js version with the PR to make it run at least), which would become "0" in the example code. Might be a good idea to have a return value for whitespace stuff, so we know when to put 1. (Well, for most "western" spaces even the EM quads it seems to be the convention in monospace fonts.)

**Comment by faho** [comment]
>Right now U+0020 gives widechar_nonprint

That's... not correct? It's [in the ascii table](https://github.com/ridiculousfish/widecharwidth/blob/1552dfc76088723d225a7aa6b2b9629bbcfa46b3/widechar_width.js#L31-L33), where everything [has width 1](https://github.com/ridiculousfish/widecharwidth/blob/1552dfc76088723d225a7aa6b2b9629bbcfa46b3/widechar_width.js#L1495-L1496).

**Comment by faho** [comment]
Ah, I think I see what you're doing.

widechar_wcwidth needs the *codepoint number*.

So you need to do

```js
widechar_wcwidth(" ".codePointAt());
```

Not

```js
widechar_wcwidth(" ");
```

**Comment by Artoria2e5** [comment]
Ah of course, a string is not a char.
