### ISSUE TITLE
Template for C (not C++) version?

### ISSUE THREAD

**Issue by RahjIII** [ridiculousfish/widecharwidth#30]
The widechar_width.h file is C++. only  Is there interest in having a template for a pure C include file (like wcwidth9.h) in the project?

**Comment by faho** [comment]
I do not believe any one of us really writes C, but if you're interested in working on it, sure, we'll take it!

**Comment by ridiculousfish** [comment]
Merged as 96d92622cfdefb96ccc7644cdf1b92c742eb5664
