### ISSUE TITLE
Suggestion: drop output down to single column to minimse git noise

### ISSUE THREAD

**Issue by SlySven** [ridiculousfish/widecharwidth#8]
https://github.com/ridiculousfish/widecharwidth/blob/5b7e9179356a8026280f53df182bd39d4b738ab0/generate.py#L227

Might I suggest changing that there may be an advantage to making this value **one** - this would have the *eventual* effect (after two iterations) of reducing the size of any git commit / difference between two different versions so that only ranges that ARE different get picked out as being different. Currently a single change of just one character added or removed (as an singleton) can produce a sizeable difference - I mean fancy trying to see where the changes are in this part of the unassigned character ranges:
![image](https://user-images.githubusercontent.com/6163092/77865172-e2f02700-7224-11ea-800d-97c852e241d6.png)

I suppose a branch parallel to master with this sole change is another possibility...

**Comment by ridiculousfish** [comment]
Sure, I'll merge a PR if you have the time!
