### ISSUE TITLE
Additional (negative return value) classification needed for "Non-characters"?

### ISSUE THREAD

**Issue by SlySven** [ridiculousfish/widecharwidth#9]
Is there any merit in detecting and returning a further special value should the `widechar_wcwidth(...)` function be called with a code-point value that is formally declared to be a "**[non-character](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Non-characters)**" these are obviously *never* going to be assigned but they are distinct from the "unassigned" codepoints indicated by a `widechar_unassigned` return value?

Or, given the suggested width to use for those (of `0`) is this an implementation detail that this project should not need to cover?

**Comment by ridiculousfish** [comment]
I think it comes down to use cases. If you have a need to distinguish these I'd be happy to add it or merge a PR!

**Comment by faho** [comment]
Since we don't have a use case (and as far as I can tell we already return a width of 0), this doesn't seem to be needed.

If anyone has a use case, we can of course reopen this.

**Comment by SlySven** [comment]
Actually this issue got duplicated by myself in #10 and wasfixed - by https://github.com/ridiculousfish/widecharwidth/commit/82e12385ad57b2fe6990249ebb2426da0e771330 ... 😀
